#### Linear Regression
##### Linear Regression is a statistical method used to model the relationship between a dependent variable (Y) and an independent variable (X) by fitting a straight line.

##### Equation of Linear Regression

$$
Y = a + bX
$$

Where:

- $Y$ = Dependent variable  
- $X$ = Independent variable  
- $a$ = Intercept  
- $b$ = Slope (regression coefficient)

##### Simple Linear Regression
- ###### Simple Linear Regression is a statistical method used to model the relationship between one independent variable and one independent variable. It is used to predict the value of Y using X and to understand the linear relationship between variables.

##### Multiple Linear Regression 
##### Multiple Linear Regression is a statistical method used to model the relationship between one dependent variable and two or more independent variables.
##### Equation
$$
Y = a + b_1X_1 + b_2X_2 + b_3X_3 + \dots + b_nX_n


##### Example Problem
##### A biomedical Engineer wants to predict Blood Pressure (Y) using:
- Age ($X_1$)  
- Body Mass Index (BMI) ($X_2$)   $$

In [53]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from scipy import stats # imports the statistics module from SciPy.



In [55]:
flights = sns.load_dataset("flights")

In [57]:
lm = LinearRegression()

In [59]:
x = flights[['year']] #H=x is independent variable (Input) and y is Dependent variable (Output). We use double big bracket to keep it in DataFrame Format as Machie learning models expect 2D input  
y = flights[['passengers']]

In [61]:
lm.fit(x,y)

LinearRegression()

In [63]:
Yhat = lm.predict(x) # Predicts values of Y.

In [65]:
print(Yhat)

[[104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [264.33663559]
 [264.33663559]
 [264.33

In [67]:
lm.intercept_

array([-62115.06371406])

In [69]:
lm.coef_

array([[31.92395105]])

In [71]:
#MUltiple Linear Regression

In [73]:
from sklearn.linear_model import LinearRegression

In [75]:
lm = LinearRegression()

In [78]:
import pandas as pd

data = {
    "S.No": [1,2,3,4,5,6,7,8,9,10,11],
    "A": [2.0,4.0,6.0,8.0,10.0,12.0,14.0,16.0,18.0,20.0,None],
    "B": [1,3,5,7,9,11,13,15,17,19,21],
    "C": [5,10,15,20,25,30,35,40,45,50,55],
    "D": [3.0,6.0,9.0,12.0,15.0,18.0,21.0,24.0,27.0,30.0,None],
    "E": [4,8,12,16,20,24,28,32,36,40,44],
    "length": [45,43,66,78,32,12,54,67,77,89,45],
    "ABC": ["sedan","wagon","hatchback","wagon","sedan","convertible","suv","convertible","suv","hatchback",None],
    "XYZ": ["rwd","fwd","4wd","4wd","rwd","fwd","fwd","rwd","4wd","rwd",None]
}

df = pd.DataFrame(data)

print(df)

    S.No     A   B   C     D   E  length          ABC   XYZ
0      1   2.0   1   5   3.0   4      45        sedan   rwd
1      2   4.0   3  10   6.0   8      43        wagon   fwd
2      3   6.0   5  15   9.0  12      66    hatchback   4wd
3      4   8.0   7  20  12.0  16      78        wagon   4wd
4      5  10.0   9  25  15.0  20      32        sedan   rwd
5      6  12.0  11  30  18.0  24      12  convertible   fwd
6      7  14.0  13  35  21.0  28      54          suv   fwd
7      8  16.0  15  40  24.0  32      67  convertible   rwd
8      9  18.0  17  45  27.0  36      77          suv   4wd
9     10  20.0  19  50  30.0  40      89    hatchback   rwd
10    11   NaN  21  55   NaN  44      45         None  None


In [90]:
df = df.dropna() # Our data has NaN which models can not work with so we are using this.

In [92]:
X = df[['A', 'B', 'C']]
Y = df[['D']]

In [94]:
lm.fit(X,Y)

LinearRegression()

In [96]:
yhat = lm.predict(X)

In [98]:
print(Yhat)

[[104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [104.71688034]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [136.64083139]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [168.56478244]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [200.48873349]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [232.41268454]
 [264.33663559]
 [264.33663559]
 [264.33

In [100]:
lm.intercept_

array([0.18181818])

In [102]:
lm.coef_


array([[0.18181818, 0.18181818, 0.45454545]])

##### Regression Plot
##### A regression Plot is a graph that shows the relationship between Independent variable (X)