#### Polynomial Regression
##### Polynomial Regression is an extension of Linear Regression where we fit a curve instead of a straight line.

#### Curvilinear Relationship 
##### A curvilinear relationship is non linear relationship where the chnage between two variables follows a curved pattern instead of straight line.

In [14]:
import numpy as np
x = np.random.randn(100)
y =np.random.randn(100)

In [22]:
f = np.polyfit(x, y, 3) # Fit a polynomia of degree 3 (cubic curve) to data (x,y). We can change the order.
p = np.poly1d(f) # This converts the coefficient into a polynomial function.

In [24]:
print(p)

          3          2
-0.05388 x - 0.0334 x + 0.3034 x - 0.03947


In [100]:
from sklearn.preprocessing import PolynomialFeatures
from scipy import stats
import seaborn as sns
from sklearn.linear_model import LinearRegression
flights = sns.load_dataset("flights")

In [102]:
pr = PolynomialFeatures(degree = 2, include_bias = False)
x_polly = pr.fit_transform(flights[['year', 'passengers']])

In [104]:
print(x_polly)

[[1.949000e+03 1.120000e+02 3.798601e+06 2.182880e+05 1.254400e+04]
 [1.949000e+03 1.180000e+02 3.798601e+06 2.299820e+05 1.392400e+04]
 [1.949000e+03 1.320000e+02 3.798601e+06 2.572680e+05 1.742400e+04]
 [1.949000e+03 1.290000e+02 3.798601e+06 2.514210e+05 1.664100e+04]
 [1.949000e+03 1.210000e+02 3.798601e+06 2.358290e+05 1.464100e+04]
 [1.949000e+03 1.350000e+02 3.798601e+06 2.631150e+05 1.822500e+04]
 [1.949000e+03 1.480000e+02 3.798601e+06 2.884520e+05 2.190400e+04]
 [1.949000e+03 1.480000e+02 3.798601e+06 2.884520e+05 2.190400e+04]
 [1.949000e+03 1.360000e+02 3.798601e+06 2.650640e+05 1.849600e+04]
 [1.949000e+03 1.190000e+02 3.798601e+06 2.319310e+05 1.416100e+04]
 [1.949000e+03 1.040000e+02 3.798601e+06 2.026960e+05 1.081600e+04]
 [1.949000e+03 1.180000e+02 3.798601e+06 2.299820e+05 1.392400e+04]
 [1.950000e+03 1.150000e+02 3.802500e+06 2.242500e+05 1.322500e+04]
 [1.950000e+03 1.260000e+02 3.802500e+06 2.457000e+05 1.587600e+04]
 [1.950000e+03 1.410000e+02 3.802500e+06 2.74950

#### Sample Evaluation
##### Sample Evaluation is the process of measuring model  performance using a subset of data (test sample) that was not used duringg training.

##### Why does we use It ?
- To check model performance on unseen data.
- To detect the overfitting.
- To measure real- world prediction accuraccy.
- To measure model generalization

##### Dta Splitting
##### Dataset is divided into:
- Training Sample(70-80%) ---> Used to train model.
- Testing Sample (20-30%) ---> Used for  evaluation.

##### Commonn Evaluation Metrices (Regression)
- $R^2$ Score -----> Goodness of fit.
- Mean of Squared Errors (MSE) ----> Average squared error.

#### Mean Squared Error (MSE)
##### Mean Squared Error (MSE) is a regression evaluation metric that measures the average of the squared diffrences between actual and predicted values.

In [108]:
from sklearn.metrics import mean_squared_error # It imports the Mean Squared Error (MSE) function from the sklearn.metrics module. 
flights = sns.load_dataset("flights")

In [110]:
mean_squared_error(flights['year'], flights['passengers'], multioutput = 'raw_values')

array([2816493.32638889])

In [112]:
mean_squared_error(flights['year'], flights['passengers'], multioutput = 'uniform_average')

2816493.326388889

In [114]:
mean_squared_error(flights['year'], flights['passengers'], squared = True)

C:\Users\Aaditya\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


2816493.326388889

In [116]:
mean_squared_error(flights['year'], flights['passengers'], squared = False) #It gives the root MSE.

C:\Users\Aaditya\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


1678.2411407151503

$R^2$
##### $R^2$ is a regression evaluation metric that measures how well the independent variable (s) explain the variation in the dependent variable. It values always lies between 0 and 1.


In [119]:
x = flights[['year']]
y = flights[['passengers']]

In [121]:
lm = LinearRegression()

In [123]:
lm.fit(x, y)

LinearRegression()

In [125]:
lm.score(x, y)

0.8497591833132266